# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlusWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 203)
        MainWindow.setStyleSheet("background-color: rgb(241, 231, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setStyleSheet("QPushButton{\n"
"    background-color: rgb(230, 208, 255);\n"
"    border-radius: 15px;\n"
"    padding: 5px;\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(157, 0, 255);\n"
"}")
        self.back.setObjectName("back")
        self.horizontalLayout_3.addWidget(self.back)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.vvodtext = QtWidgets.QLineEdit(self.centralwidget)
        self.vvodtext.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.vvodtext.setObjectName("vvodtext")
        self.horizontalLayout_3.addWidget(self.vvodtext)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.otzyv = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.otzyv.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.otzyv.setObjectName("otzyv")
        self.horizontalLayout_4.addWidget(self.otzyv)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.r2 = QtWidgets.QRadioButton(self.centralwidget)
        self.r2.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r2.setObjectName("r2")
        self.gridLayout.addWidget(self.r2, 0, 1, 1, 1)
        self.r1 = QtWidgets.QRadioButton(self.centralwidget)
        self.r1.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r1.setObjectName("r1")
        self.gridLayout.addWidget(self.r1, 0, 0, 1, 1)
        self.r8 = QtWidgets.QRadioButton(self.centralwidget)
        self.r8.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r8.setObjectName("r8")
        self.gridLayout.addWidget(self.r8, 2, 1, 1, 1)
        self.r9 = QtWidgets.QRadioButton(self.centralwidget)
        self.r9.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r9.setObjectName("r9")
        self.gridLayout.addWidget(self.r9, 2, 2, 1, 1)
        self.r4 = QtWidgets.QRadioButton(self.centralwidget)
        self.r4.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r4.setObjectName("r4")
        self.gridLayout.addWidget(self.r4, 1, 0, 1, 1)
        self.r6 = QtWidgets.QRadioButton(self.centralwidget)
        self.r6.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r6.setObjectName("r6")
        self.gridLayout.addWidget(self.r6, 1, 2, 1, 1)
        self.r7 = QtWidgets.QRadioButton(self.centralwidget)
        self.r7.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r7.setObjectName("r7")
        self.gridLayout.addWidget(self.r7, 2, 0, 1, 1)
        self.r3 = QtWidgets.QRadioButton(self.centralwidget)
        self.r3.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r3.setObjectName("r3")
        self.gridLayout.addWidget(self.r3, 0, 2, 1, 1)
        self.r5 = QtWidgets.QRadioButton(self.centralwidget)
        self.r5.setStyleSheet("QRadioButton{\n"
"    background-color: rgb(241, 231, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 70px;\n"
"    height: 15px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: rgb(255, 148, 218);\n"
"}")
        self.r5.setObjectName("r5")
        self.gridLayout.addWidget(self.r5, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.ocenka = QtWidgets.QSpinBox(self.centralwidget)
        self.ocenka.setStyleSheet("QSpinBox{\n"
"    background-color: rgb(230, 208, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 20px;\n"
"    height: 15px;\n"
"}\n"
"QSpinBox:hover{\n"
"    background-color: rgb(157, 0, 255);\n"
"}")
        self.ocenka.setObjectName("ocenka")
        self.horizontalLayout.addWidget(self.ocenka)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.statusbox = QtWidgets.QComboBox(self.centralwidget)
        self.statusbox.setStyleSheet("QComboBox{\n"
"    background-color: rgb(230, 208, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 80px;\n"
"    height: 15px;\n"
"}\n"
"QComboBox:hover{\n"
"    background-color: rgb(157, 0, 255);\n"
"}")
        self.statusbox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.statusbox.setObjectName("statusbox")
        self.statusbox.addItem("")
        self.statusbox.addItem("")
        self.statusbox.addItem("")
        self.statusbox.addItem("")
        self.statusbox.addItem("")
        self.statusbox.addItem("")
        self.horizontalLayout.addWidget(self.statusbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.btnadd = QtWidgets.QPushButton(self.centralwidget)
        self.btnadd.setStyleSheet("QPushButton{\n"
"    background-color: rgb(230, 208, 255);\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    width: 60px;\n"
"    height: 15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(157, 0, 255);\n"
"}")
        self.btnadd.setObjectName("btnadd")
        self.horizontalLayout_2.addWidget(self.btnadd)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "add title"))
        self.back.setText(_translate("MainWindow", "<-"))
        self.label_3.setText(_translate("MainWindow", " название:  "))
        self.label_4.setText(_translate("MainWindow", "введите отзыв:     "))
        self.r2.setText(_translate("MainWindow", "книга"))
        self.r1.setText(_translate("MainWindow", "фильм"))
        self.r8.setText(_translate("MainWindow", "комикс"))
        self.r9.setText(_translate("MainWindow", "мультфильм"))
        self.r4.setText(_translate("MainWindow", "аниме"))
        self.r6.setText(_translate("MainWindow", "маньхуа"))
        self.r7.setText(_translate("MainWindow", "сериал"))
        self.r3.setText(_translate("MainWindow", "манхва"))
        self.r5.setText(_translate("MainWindow", "манга"))
        self.label.setText(_translate("MainWindow", "  оценнка:"))
        self.label_2.setText(_translate("MainWindow", "/10          "))
        self.label_5.setText(_translate("MainWindow", "введите статус:"))
        self.statusbox.setItemText(0, _translate("MainWindow", "буду смотреть"))
        self.statusbox.setItemText(1, _translate("MainWindow", "смотрю"))
        self.statusbox.setItemText(2, _translate("MainWindow", "просмотрено"))
        self.statusbox.setItemText(3, _translate("MainWindow", "буду читать"))
        self.statusbox.setItemText(4, _translate("MainWindow", "читаю"))
        self.statusbox.setItemText(5, _translate("MainWindow", "прочитано"))
        self.btnadd.setText(_translate("MainWindow", "добавить"))
